import { useState, useEffect } from 'react';

const MOVIE_POOL = [
  { title: "Star Wars: A New Hope", quote: "May the Force be with you." },
  { title: "The Matrix", quote: "There is no spoon." },
  { title: "Avatar", quote: "I see you." },
  { title: "Titanic", quote: "I'll never let go, Jack." },
  { title: "Inception", quote: "Your mind is the scene of the crime." },
  { title: "Jaws", quote: "You're gonna need a bigger boat." },
  { title: "The Lion King", quote: "Remember who you are." },
  { title: "The Dark Knight", quote: "Why so serious?" },
  { title: "Toy Story", quote: "To infinity and beyond!" },
  { title: "Gladiator", quote: "Are you not entertained?" },
  { title: "The Wizard of Oz", quote: "There's no place like home." },
  { title: "Forrest Gump", quote: "Life is like a box of chocolates." },
  { title: "The Terminator", quote: "I'll be back." },
  { title: "Back to the Future", quote: "Roads? Where we're going, we don't need roads." },
  { title: "Jurassic Park", quote: "Welcome to Jurassic Park." },
  { title: "Spider-Man", quote: "With great power comes great responsibility." },
  { title: "Finding Nemo", quote: "Just keep swimming." },
  { title: "The Avengers", quote: "I am Iron Man." },
  { title: "The Godfather", quote: "I'm gonna make him an offer he can't refuse." },
  { title: "The Shining", quote: "Here's Johnny!" },
  { title: "E.T. the Extra-Terrestrial", quote: "E.T. phone home." },
  { title: "Scarface", quote: "Say 'hello' to my little friend!" },
  { title: "Fight Club", quote: "The first rule of Fight Club is: You do not talk about Fight Club." },
  { title: "Pulp Fiction", quote: "They call it a Royale with cheese." },
  { title: "The Sixth Sense", quote: "I see dead people." },
  { title: "Braveheart", quote: "They may take our lives, but they'll never take our freedom!" },
  { title: "Rocky", quote: "Yo, Adrian!" },
  { title: "The Shawshank Redemption", quote: "Get busy living, or get busy dying." },
  { title: "Top Gun", quote: "I feel the need... the need for speed!" },
  { title: "Shrek", quote: "Ogres are like onions." },
  { title: "Monsters Inc", quote: "Put that thing back where it came from, or so help me!" },
  { title: "Up", quote: "Adventure is out there!" },
  { title: "The Incredibles", quote: "Where is my super suit?" },
  { title: "Cars", quote: "Ka-chow!" },
  { title: "Home Alone", quote: "Keep the change, ya filthy animal." },
  { title: "Elf", quote: "The best way to spread Christmas cheer is singing loud for all to hear." },
  { title: "Mean Girls", quote: "On Wednesdays we wear pink." },
  { title: "The Hunger Games", quote: "May the odds be ever in your favor." },
  { title: "Harry Potter and the Sorcerer's Stone", quote: "You're a wizard, Harry." },
  { title: "Ghostbusters", quote: "Who you gonna call?" },
  { title: "The Princess Bride", quote: "Hello. My name is Inigo Montoya. You killed my father. Prepare to die." },
  { title: "The Breakfast Club", quote: "Don't you forget about me." },
  { title: "Ferris Bueller's Day Off", quote: "Life moves pretty fast." },
  { title: "The Hangover", quote: "What happens in Vegas stays in Vegas." },
  { title: "Superbad", quote: "I am McLovin." },
  { title: "Step Brothers", quote: "Did we just become best friends?" },
  { title: "Twilight", quote: "About three things I was absolutely positive." },
  { title: "Black Panther", quote: "Wakanda forever!" },
  { title: "Guardians of the Galaxy", quote: "We are Groot." },
  { title: "The Empire Strikes Back", quote: "No, I am your father." },
  { title: "Casablanca", quote: "Here's looking at you, kid." },
  { title: "The Silence of the Lambs", quote: "I ate his liver with some fava beans." },
  { title: "Psycho", quote: "A boy's best friend is his mother." },
  { title: "The Lord of the Rings: The Fellowship of the Ring", quote: "My precious." },
  { title: "Jerry Maguire", quote: "Show me the money!" },
  { title: "Apollo 13", quote: "Houston, we have a problem." },
  { title: "A Few Good Men", quote: "You can't handle the truth!" },
  { title: "Dead Poets Society", quote: "Carpe diem. Seize the day, boys." },
  { title: "Good Will Hunting", quote: "How do you like them apples?" },
  { title: "Dirty Harry", quote: "Go ahead, make my day." },
  { title: "The Green Mile", quote: "I'm tired, boss. Tired of being on the road." },
  { title: "The Truman Show", quote: "In case I don't see ya, good afternoon, good evening, and good night!" },
  { title: "The Social Network", quote: "A million dollars isn't cool. You know what's cool? A billion dollars." },
  { title: "The Wolf of Wall Street", quote: "I'm not leaving. The show goes on!" },
  { title: "Interstellar", quote: "We used to look up at the sky and wonder at our place in the stars." },
  { title: "Whiplash", quote: "Not quite my tempo." },
  { title: "The Great Gatsby", quote: "So we beat on, boats against the current." },
  { title: "Ratatouille", quote: "Anyone can cook." },
  { title: "Kung Fu Panda", quote: "There is no secret ingredient." },
  { title: "Madagascar", quote: "I like to move it, move it." },
  { title: "Despicable Me", quote: "It's so fluffy I'm gonna die!" },
  { title: "Frozen", quote: "Let it go." },
  { title: "Moana", quote: "You're welcome!" },
  { title: "The Karate Kid", quote: "Wax on, wax off." },
  { title: "The Twilight Saga: New Moon", quote: "Hold on tight, spider monkey." },
  { title: "Pirates of the Caribbean: The Curse of the Black Pearl", quote: "This is the day you will always remember as the day you almost caught Captain Jack Sparrow." },
  { title: "Men in Black", quote: "You know the difference between you and me? I make this look good." },
  { title: "The Mask", quote: "Smokin'!" },
  { title: "Dumb and Dumber", quote: "So you're telling me there's a chance!" },
  { title: "Ace Ventura: Pet Detective", quote: "All-righty then!" },
  { title: "Stand by Me", quote: "I never had any friends later on like the ones I had when I was twelve." },
  { title: "Clueless", quote: "As if!" },
  { title: "Legally Blonde", quote: "What, like it's hard?" },
  { title: "Pitch Perfect", quote: "Aca-awesome!" },
  { title: "Anchorman: The Legend of Ron Burgundy", quote: "You stay classy, San Diego." },
  { title: "Zoolander", quote: "I feel like I'm taking crazy pills!" },
  { title: "Borat", quote: "Very nice!" },
  { title: "Napoleon Dynamite", quote: "Vote for Pedro." },
  { title: "Shaun of the Dead", quote: "You've got red on you." },
  { title: "Hot Fuzz", quote: "It's all for the greater good." },
  { title: "Scott Pilgrim vs. the World", quote: "I'm in lesbians with you." },
  { title: "La La Land", quote: "Here's to the ones who dream, foolish as they may seem." },
  { title: "The Notebook", quote: "If you're a bird, I'm a bird." },
  { title: "A Star Is Born", quote: "I just wanted to take another look at you." },
  { title: "Pride and Prejudice", quote: "You have bewitched me, body and soul." },
  { title: "The Fault in Our Stars", quote: "Okay? Okay." },
  { title: "The Batman", quote: "I am vengeance." },
  { title: "Wonder Woman", quote: "It's not about deserve, it's about what you believe." },
  { title: "The Joker", quote: "I used to think that my life was a tragedy, but now I realize, it's a comedy." },
  { title: "Alien", quote: "In space, no one can hear you scream." },
  { title: "The Terminator 2: Judgment Day", quote: "Hasta la vista, baby." },
  { title: "Saving Private Ryan", quote: "Earn this." },
  { title: "Schindler's List", quote: "Whoever saves one life saves the world entire." },
  { title: "The Wizard of Oz", quote: "Toto, I've a feeling we're not in Kansas anymore." },
  { title: "Snow White and the Seven Dwarfs", quote: "Magic mirror on the wall, who is the fairest one of all?" },
  { title: "The Good, the Bad and the Ugly", quote: "When you have to shoot, shoot, don't talk." },
  { title: "Die Hard", quote: "Yippee-ki-yay, movie lover!" },
  { title: "Predator", quote: "Get to the choppa!" },
  { title: "The Departed", quote: "I'm the guy who does his job. You must be the other guy." },
  { title: "No Country for Old Men", quote: "What's the most you ever lost on a coin toss?" },
  { title: "Wall-E", quote: "Wall-E!" },
  { title: "Up", quote: "Squirrel!" },
  { title: "Finding Dory", quote: "Just keep swimming." },
  { title: "Inside Out", quote: "Do you ever look at someone and wonder, what is going on inside their head?" },
  { title: "Coco", quote: "Remember me." },
  { title: "Toy Story 3", quote: "So long, partner." },
  { title: "The Lion King 2019", quote: "Everything the light touches is our kingdom." },
  { title: "Aladdin", quote: "Do you trust me?" },
  { title: "Beauty and the Beast", quote: "Be our guest!" },
  { title: "The Little Mermaid", quote: "Part of your world." },
  { title: "Mulan", quote: "The flower that blooms in adversity is the most rare and beautiful of all." },
  { title: "Tangled", quote: "Live your dream." },
  { title: "Wreck-It Ralph", quote: "I'm bad, and that's good." },
  { title: "Zootopia", quote: "Anyone can be anything." },
  { title: "The Sixth Sense", quote: "I see dead people." },
  { title: "Signs", quote: "Swing away, Merrill." },
  { title: "The Village", quote: "Those we do not speak of." },
  { title: "The Others", quote: "No door is to be opened before the previous one is closed." },
  { title: "Scream", quote: "What's your favorite scary movie?" },
  { title: "The Ring", quote: "Seven days." },
  { title: "The Conjuring", quote: "Want to play a game of hide and clap?" },
  { title: "Insidious", quote: "It's not the house that is haunted." },
  { title: "A Nightmare on Elm Street", quote: "One, two, Freddy's coming for you." },
  { title: "Halloween", quote: "It's Halloween, everyone's entitled to one good scare." },
  { title: "The Texas Chain Saw Massacre", quote: "The saw is family." },
  { title: "Get Out", quote: "Now, sink into the floor." },
